/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:152e190f-abaf-47e0-bc2f-8cbc5c3ee1de",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4vUXyp2l7",
    "aws_user_pools_web_client_id": "2omafhp36q5ar9750cti2eb67u",
    "oauth": {}
};


export default awsmobile;
